# Generated by Django 3.1.2 on 2020-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceStrength',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
